version: "3"

services:
  grpc-gateway-sample:
    container_name: grpc_gateway_sample
    build: ./services/api
    ports:
      - "10020:9090"
    volumes:
      - ./services/api:/grpc_gateway_sample
    tty: true
    stdin_open: true

  db:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    ports:
      - "10030:5432"
    stdin_open: true
    tty: true
    volumes:
      - ./services/db/sqlite:/root/db
