version: "3"

services:
  grpc-gateway-sample:
    container_name: grpc_gateway_sample
    build: ./services/api
    ports:
      - "10020:9090"
    volumes:
      - ./services/api:/grpc_gateway_sample
    tty: true
    stdin_open: true

  db:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    ports:
      - "10030:5432"
    stdin_open: true
    tty: true
    volumes:
      - ./services/db/sqlite:/root/db

  sqlite-web:
    container_name: sqlite_web
    build: ./sqlite-web
    ports:
      - "10040:8080"
    volumes:
      - ./services/api/test.db:/data/test.db
    command: sqlite_web -H 0.0.0.0 -x /data/test.db
