version: "3"

services:
  grpc-sample:
    container_name: grpc_gateway_sample
    build: .
    ports:
      - "10020:9090"
    volumes:
      - ./aimo_sample:/grpc_gateway_sample
    tty: true
    stdin_open: true
