version: "3"

services:
  grpc-gateway-sample:
    container_name: grpc_gateway_sample
    build: ./services/api
    ports:
      - "10020:9090"
    volumes:
      - ./services/api:/grpc_gateway_sample
    tty: true
    stdin_open: true

  db:
    container_name: postgres
    build: ./services/db
    ports:
      - "10030:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
